version: 2
jobs:
  build:
    docker:
      - image: node:10
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: v1-deps
      - run: npm ci
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}
          paths:
            - ~/.npm
      - run: npm test
      # TODO switch to semantic-release-cli that will check branch before publishing
      # not every commit is going to be published
      # - run: npm run semantic-release || true
