version: 2
jobs:
  build:
    docker:
      - image: node:10
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: v1-deps
      - run: npm ci
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}
          paths:
            - ~/.npm
      - run: npm test
      # show files that will be part of the NPM package
      - run: npm run size
      # not every commit is going to be published
      - run: npm run semantic-release

workflows:
  version: 2
  test:
    jobs:
      - build
